"""Turns the outlines of a font into C# data, so the board can draw its numbers and banner
text as vector shapes. That looks the same on every device and avoids relying on the
canvas font lookup, which is unreliable for custom fonts on Android.

Usage: python3 tools/generate_glyphs.py path/to/Fredoka-Bold.ttf src/Puzzle2048.Rendering/GlyphData.g.cs
Needs: pip install fonttools
"""
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.basePen import BasePen

CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZxX+!:.-/ "


class PathPen(BasePen):
    """Collects an outline as a compact path string with M, L, Q and C commands."""

    def __init__(self, glyph_set):
        super().__init__(glyph_set)
        self.parts = []

    @staticmethod
    def _n(v):
        return str(int(round(v)))

    def _moveTo(self, p):
        self.parts.append(f"M{self._n(p[0])} {self._n(p[1])}")

    def _lineTo(self, p):
        self.parts.append(f"L{self._n(p[0])} {self._n(p[1])}")

    def _qCurveToOne(self, p1, p2):
        self.parts.append(f"Q{self._n(p1[0])} {self._n(p1[1])} {self._n(p2[0])} {self._n(p2[1])}")

    def _curveToOne(self, p1, p2, p3):
        self.parts.append("C" + " ".join(self._n(v) for p in (p1, p2, p3) for v in p))

    def _closePath(self):
        self.parts.append("Z")


def main(font_path, out_path):
    font = TTFont(font_path)
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    upm = font["head"].unitsPerEm
    ascent = font["hhea"].ascent
    descent = font["hhea"].descent
    cap_height = getattr(font["OS/2"], "sCapHeight", 0) or int(upm * 0.7)

    lines = []
    for ch in CHARS:
        name = cmap[ord(ch)]
        pen = PathPen(glyph_set)
        glyph_set[name].draw(pen)
        advance = font["hmtx"][name][0]
        path = "".join(pen.parts)
        esc = ch.replace("\\", "\\\\").replace("\"", "\\\"")
        lines.append(f'        [\'{esc}\'] = new GlyphShape({advance}, "{path}"),')

    with open(out_path, "w") as f:
        f.write("// <auto-generated>\n")
        f.write("// Produced by tools/generate_glyphs.py from Fredoka Bold (SIL Open Font License 1.1).\n")
        f.write("// Do not edit by hand.\n")
        f.write("// </auto-generated>\n")
        f.write("namespace Puzzle2048.Rendering;\n\n")
        f.write("internal static partial class GlyphData\n{\n")
        f.write(f"    public const int UnitsPerEm = {upm};\n")
        f.write(f"    public const int CapHeight = {cap_height};\n")
        f.write(f"    public const int Ascent = {ascent};\n")
        f.write(f"    public const int Descent = {descent};\n\n")
        f.write("    public static readonly Dictionary<char, GlyphShape> Shapes = new()\n    {\n")
        f.write("\n".join(lines))
        f.write("\n    };\n}\n")
    print("wrote", out_path, len(CHARS), "glyphs, upm", upm, "capHeight", cap_height)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
